version: '3'
services:
  backend:
    build: ./services/backend/app
    ports:
      - 5001:5000
    volumes:
      - ./services/backend/app:/app
      - uploaded-files:/app/uploaded-files
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    build: ./services/backend/celery
    volumes:
      - ./services/backend/celery:/celery
      - uploaded-files:/celery/uploaded-files
volumes:
  uploaded-files:
